from mcstats import mcstats

# Better sorting because many entries needed
building_blocks = [
    "minecraft:.+_bricks",
    "minecraft:quartz_block",
    "minecraft:.+_quartz_block",
    "minecraft:quartz_pillar",
    "minecraft:quartz_bricks",
    "minecraft:hay_block",
    "minecraft:.+_carpet",
    "minecraft:terracotta",
    "minecraft:.+_terracotta",
    "minecraft:polished_granite",
    "minecraft:sea_lantern",
    "minecraft:polished_andesite",
    "minecraft:prismarine",
    "minecraft:dark_prismarine",
    "minecraft:bone_block",
    "minecraft:.+_wart_block",
    "minecraft:purpur_block",
    "minecraft:purpur_pillar",
    "minecraft:.+_concrete_powder",
    "minecraft:.+_concrete",
    "minecraft:.+_wood",
    "minecraft:.+_log",
    "minecraft:.+_stem",
    "minecraft:.+_hyphae",
    "minecraft:emerald_block",
    "minecraft:coal_block",
    "minecraft:chain",
    "minecraft:netherite_block",
    "minecraft:polished_blackstone",
    "minecraft:chiseled_polished_blackstone",
    "minecraft:.*glass_pane",
    "minecraft:.*stained_glass",
    "minecraft:.+_stairs",
    "minecraft:bricks",
    "minecraft:bookshelf",
    "minecraft:snow_block",
    "minecraft:jack_o_lantern",
    "minecraft:glowstone",
    "minecraft:lapis_block",
    "minecraft:.*sandstone",
    "minecraft:.+_slab",
    "minecraft:.*glass",
    "minecraft:amethyst_block",
    "minecraft:.+_wool",
    "minecraft:dripstone_block",
    "minecraft:.*planks",
    "minecraft:polished_deepslate",
    "minecraft:chiseled_deepslate",
    "minecraft:polished_diorite",
    "minecraft:.*deepslate_tiles",
    "minecraft:copper_block",
    "minecraft:exposed_copper",
    "minecraft:weathered_copper",
    "minecraft:oxidized_copper",
    "minecraft:.*cut_copper",
    "minecraft:waxed_copper_block",
    "minecraft:waxed_exposed_copper",
    "minecraft:waxed_weathered_copper",
    "minecraft:waxed_oxidized_copper",
    "minecraft:waxed_cut_copper",
    "minecraft:waxed_exposed_cut_copper",
    "minecraft:waxed_weathered_cut_copper",
    "minecraft:waxed_oxidized_cut_copper",
    "minecraft:.*iron_block",
    "minecraft:.*gold_block",
    "minecraft:diamond_block",
    "minecraft:cobblestone",
    "minecraft:stone",
    "minecraft:mossy_cobblestone",
]

mcstats.registry.append(
    mcstats.MinecraftStat(
        "place_buildblocks",
        {
            "unit": "int",
        },
        # subtract mined from placed
        mcstats.StatSumMatchReader(["minecraft:used"], building_blocks),
    )
)
